name: Terraform

on:
  # schedule:
  #   - cron:  '30 23 * * 0-4'
  #   - cron:  '0 1 * * 1-5'
  workflow_dispatch:
    inputs:
      do_apply:
        description: 'apply? or not(destroy)'
        required: true
        type: boolean

env:
  TF_VAR_project_id          : ${{ vars.project_id }}
  TF_VAR_region              : ${{ vars.region }}
  TF_VAR_zone                : ${{ vars.zone }}
  TF_VAR_service_account_id  : ${{ vars.service_account_id }}
  TF_VAR_service_account_name: ${{ vars.service_account_name }}
  TF_VAR_instance_name       : ${{ vars.instance_name }}
  TF_VAR_machine_type        : ${{ vars.machine_type }}
  TF_VAR_image               : ${{ vars.image }}
  TF_VAR_tags                : ${{ vars.tags }}
  TF_VAR_rdp_port            : ${{ vars.rdp_port }}
  TF_VAR_ssh_port            : ${{ vars.ssh_port }}
  TF_VAR_instance_user       : ${{ vars.instance_user }}
  TF_VAR_device              : ${{ vars.device }}
  TF_VAR_disk_name           : ${{ vars.disk_name }}
  TF_BUCKET_NAME             : ${{ vars.bucket_name }}
  TF_BUCKET_PREFIX           : ${{ vars.bucket_prefix }}

jobs:
  create_gce:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }} # 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_IAM_ROLE }} # 'arn:aws:iam::<AWSアカウントID>:role/<IAMロール名>'

      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive
      - run: terraform init -backend-config="bucket=$TF_BUCKET_NAME" -backend-config="prefix=$TF_BUCKET_PREFIX"
      - run: terraform validate
      - run: terraform plan -no-color -lock-timeout=60m

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && ((github.event_name == 'schedule' && github.event.schedule == '30 23 * * 0-4') || (github.event_name == 'workflow_dispatch' && inputs.do_apply))
        run: terraform apply -auto-approve -input=false
      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main' && ((github.event_name == 'schedule' && github.event.schedule == '0 1 * * 1-5') || (github.event_name == 'workflow_dispatch' && !inputs.do_apply))
        run: terraform destroy -auto-approve -input=false
